name: Build And Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      # - name: Install pnpm
      #   uses: https://github.com/pnpm/action-setup@v2
      #   with:
      #     version: latest
      - name: Install dependencies
        run: npm install
      - name: Build Site
        run: npm run export
      - name: Deploy
        uses: https://github.com/wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
            username: "${{ secrets.SFTP_USER }}"
            server: "${{ secrets.SFTP_HOST }}"
            port: "${{ secrets.SFTP_PORT }}"
            password: "${{ secrets.SFTP_PASS }}"
            local_path: './out/*'
            remote_path: '/www'
            sftp_only: true
